# NBDFinder Default Configuration
# ==============================
# Thresholds, loop ranges, and algorithm parameters

# Processing parameters
processing:
  chunk_size: 100000  # 100kb chunks for large sequences
  overlap_size: 1000  # 1kb overlap to handle motifs spanning chunks
  max_workers: null   # Use all available CPU cores
  hyperscan_enabled: true
  
# Global thresholds
thresholds:
  min_motif_length: 10
  max_motif_length: 1000
  min_score_threshold: 0.1
  significance_threshold: 0.05
  
# Loop and repeat ranges  
loops:
  min_loop_length: 1
  max_loop_length: 50
  min_arm_length: 6
  max_arm_length: 50
  
# REZ (R-loop Exiting Zone) parameters
rez_params:
  min_gc_content: 0.6
  min_length: 20
  max_length: 100
  gc_window_size: 10
  
# Scoring algorithm parameters
scoring:
  g4hunter:
    window_size: 25
    default_threshold: 1.2
    normalization: "length_adjusted"
    
  z_seeker:
    dinucleotide_weights:
      CG: 1.0
      GC: 1.0
      CA: 0.5
      TG: 0.5
    mismatch_penalty: -0.5
    
  curvature:
    at_weight: 1.0
    tract_bonus: 0.2
    spacing_penalty: 0.1
    
# Export format defaults
export:
  bed_precision: 3
  csv_separator: ","
  include_sequence: true
  include_scores: true
  
# Cache settings
cache:
  enabled: true
  max_size_mb: 500
  ttl_hours: 24
  
# Performance settings
performance:
  enable_simd: true
  vectorization: true
  memory_limit_gb: 8